# Generated by Django 5.2.5 on 2025-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0003_remove_product_category_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('sharee', 'Sharee'), ('panjabi', 'Panjabi')], max_length=10),
        ),
    ]
