# Generated by Django 5.2.5 on 2025-08-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_remove_product_available_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('saree', 'Saree'), ('panjabi', 'Panjabi')], max_length=10),
        ),
    ]
